#!/bin/bash

set -ex

docker run -it --rm \
  --network debezium-sharing_default \
  --link dbz_db_olap:postgres \
  debezium/postgres:11 \
  sh -c "psql postgresql://postgres:password@postgres:5432/olap"
