#!/bin/bash

set -ex

curl -i -X POST -H "Accept:application/json" -H "Content-Type:application/json" http://localhost:8083/connectors/ -d '
{
  "name": "dbz-pg-connector",
  "config": {
          "connector.class": "io.debezium.connector.postgresql.PostgresConnector",
          "tasks.max": "1",
          "group.id": "test",
          "database.hostname": "postgres",
          "database.port": "5432",
          "database.user": "postgres",
          "database.password": "password",
          "database.dbname": "dbz_examples",
          "database.server.name": "dbz_postgres",
          "schema.include.list": "public",
          "heartbeat.interval.ms": "1000",
          "table.include.list": "public.customers",
          "database.history.kafka.bootstrap.servers": "kafka:9092",
          "key.converter": "org.apache.kafka.connect.json.JsonConverter",
          "key.converter.schemas.enabled": "false",
          "value.converter": "org.apache.kafka.connect.json.JsonConverter",
          "value.converter.schemas.enabled": "false",
          "plugin.name": "pgoutput"
  }
}'
