#!/bin/bash

set -ex

curl -i -X POST -H "Accept:application/json" -H "Content-Type:application/json" http://localhost:8083/connectors/ -d '
{
  "name": "dbz-sink-connector",
  "config": {
          "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
          "tasks.max": "1",
          "connection.url": "jdbc:postgresql://172.24.0.1:5432/dbz_sink",
          "connection.user": "dbz",
          "connection.password": "dbz",
          "topics": "customers,products",
          "auto.create": "true",
          "insert.mode": "upsert",
          "pk.fields": "id",
          "pk.mode": "record_value"
  }
}'
