#!/bin/bash

set -ex

db_file=$(pwd)/db/schema.sql

docker run -it --rm \
  --network debezium-sharing_default \
  --link dbz_postgres:postgres \
  -v "$db_file:/schema.sql" \
  debezium/postgres:11 \
  sh -c "psql postgresql://postgres:password@postgres:5432/dbz_examples < /schema.sql"
