#!/bin/bash

set -ex

docker run -it --rm --network dbz_network \
  --link dbz_zookeeper:zookeeper \
  debezium-playground_kafka \
  sh -c "/kafka/bin/kafka-console-consumer.sh --bootstrap-server 172.24.0.1:9092 --property print.key=true --property fetch.min.bytes=1 --topic customers $@ | /usr/bin/jq '.'"
