#!/bin/bash

set -ex

docker run -it --rm --network debezium-sharing_default \
  --link dbz_zookeeper:zookeeper \
  --link dbz_kafka:kafka \
  debezium-sharing_kafka \
  sh -c "/kafka/bin/kafka-console-consumer.sh --bootstrap-server kafka:9092 --property print.key=true --property fetch.min.bytes=1 --topic dbz_postgres.public.customers $@ | /usr/bin/jq '.'"
